<a href="https://colab.research.google.com/github/wonjae124/python/blob/main/cuda_loss_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
2/2.0

1.0

In [2]:
import torch
import torch.nn as nn

In [2]:
2/2

1.0

In [31]:
A = torch.tensor([[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
, dtype=torch.int)

B = torch.tensor([[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
, dtype=torch.int)
A

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

In [34]:
A = torch.tensor([[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]])

B = torch.tensor([[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]])
A

tensor([[[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000],
         [0.7000, 0.6000, 0.5000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000],
         [0.7000, 0.6000, 0.5000]]])

In [35]:
B

tensor([[[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.1000],
         [0.7000, 0.6000, 0.5000]],

        [[0.1000, 0.2000, 0.9000],
         [0.3000, 0.5000, 0.2000],
         [0.7000, 0.6000, 0.5000]]])

In [28]:
loss = nn.MSELoss().to(torch.device('cuda'))
input = torch.randn(3, 5, requires_grad=True, device = torch.device('cuda'))
target = torch.randn(3, 5, device = torch.device('cuda'))
output = loss(input, target)
output.backward()

In [29]:
output

tensor(1.9217, device='cuda:0', grad_fn=<MseLossBackward0>)

In [25]:
loss = nn.MSELoss(torch.device('cuda'))


NameError: ignored