<a href="https://colab.research.google.com/github/wonjae124/python/blob/main/Numpy%EC%9D%98_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%98%95_dtype%EA%B3%BC_astype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://engineer-mole.tistory.com/85 

import numpy as np

a = np.array([1,2,3], dtype=np.int64)
print(a.dtype)

a = np.array([1,2,3], dtype='int64')
print(a.dtype)

a = np.array([1,2,3], dtype='i8')
print(a.dtype)

int64
int64
int64


In [ ]:
print(int is np.int)
a = np.array([1,2,3],dtype=int)
print(a.dtype)
a = np.array([1,2,3],dtype='int')
print(a.dtype)

True
int64
int64


In [ ]:
#파이썬 object형
a_object = np.array([1,0.1,'one'], dtype=object)
print(a_object)
print(a_object.dtype)

print(type(a_object[0]))
print(type(a_object[1]))
print(type(a_object[2]))

a_object[2] = 'oneONE'
print(a_object)

[1 0.1 'one']
object
<class 'int'>
<class 'float'>
<class 'str'>
[1 0.1 'oneONE']


In [ ]:
#astype()를 사용한 데이터 타입 ( dtype ) 변환
a = np.array([1,2,3])
print(a)
print(a.dtype)

a_float = a.astype(np.float32)
print(a_float)
print(a_float.dtype)

print(a)
print(a.dtype)

[1 2 3]
int64
[1. 2. 3.]
float32
[1 2 3]
int64


In [ ]:
a_float = a.astype(float)
print(a_float)
print(a_float.dtype)

a_str = a.astype('str')
print(a_str)
print(a_str.dtype)

a_int = a.astype('int32')
print(a_int)
print(a_str.dtype)

[1. 2. 3.]
float64
['1' '2' '3']
<U21
[1 2 3]
<U21


In [27]:
# astype에서 float에서 int로 캐스트. 소수점 이하는 잘리고 마이너스 값은 0으로 반올림 됨
 
a = np.arange(50).reshape((5,10))/10-2
print(a)
print(a.dtype)

a_int = a.astype('int64')
print(a_int)
print(a_int.dtype)

# 사사오입. 앞자리가 짝수면 내림하고 홀수면 올림한다.
print( round(4.5) )
print( round(3.5) )

[[-2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1]
 [-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1]
 [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]
 [ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]
 [ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9]]
float64
[[-2 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]]
int64
4
4
