<a href="https://colab.research.google.com/github/wonjae124/python/blob/main/numpy_shape_vs_tenosr_shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np
import timeit
import torch

In [3]:
array1d = np.array([1,2,3,4])
print(array1d)
print(type(array1d))
print(array1d.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [8]:
gen0 = [100, 200]
gen1 = [50, 0]
gen2 = [350, 100]
expression_data = [gen0, gen1, gen2]
expression_data

[[100, 200], [50, 0], [350, 100]]

In [22]:
print(len(gen1)) #리스트의 크기를 구하는 방법으로, shape 없고 len만 가능
print(type(gen1))

2
<class 'list'>


In [24]:
print(len(expression_data))
print(type(expression_data))

3
<class 'list'>


In [31]:
print(expression_data[0][0], expression_data[0][1])
print(expression_data[1][0],expression_data[1][1])
print(expression_data[2][0],expression_data[2][1])

100 200
50 0
350 100


In [34]:
array2d = np.array(expression_data)
print(array2d)
print(array2d.shape)  # (height, width) = (3. 2)
print(type(array2d))
print(array2d.ndim)

[[100 200]
 [ 50   0]
 [350 100]]
(3, 2)
<class 'numpy.ndarray'>
2


##List보다 array가 연산속도가 빠르다

In [39]:
array = np.arange(1e6)
list_array = array.tolist()
list_array
print(type(array))
print(type(list_array))

<class 'numpy.ndarray'>
<class 'list'>


In [40]:
%timeit -n10 y = [val * 5 for val in list_array]

10 loops, best of 5: 103 ms per loop


In [41]:
%timeit -n10 x = array*5 # array가 list보다 50배 빠르다.

10 loops, best of 5: 2.25 ms per loop


## For문에서 일일히 하나씩 더 하는 것보다, 벡터로 만들어서 행렬계산하는게 더 빠르다.

In [45]:
x = np.array([1, 2, 3, 4])
print(x*2)
print(x.shape)

[2 4 6 8]
(4,)


In [47]:
y= np.array([0, 1, 2, 1])
print(y.shape)
print(x+y)
print((x+y).shape)

(4,)
[1 3 5 5]
(4,)


## Broadcasting. 두 행렬간의 효율적인 연산


In [58]:
x = np.array([1, 2, 3, 4])
print(x,'\n')

x = np.reshape(x, (len(x),1)) # (4, )-> (4,1)
print(x,'\n')

print(x.shape)

[1 2 3 4] 

[[1]
 [2]
 [3]
 [4]] 

(4, 1)


In [59]:
y = np.array([0, 1, 2, 1])

y = np.reshape(y, (1, len(y))) #(4,) ->(1, 4)
print(y)

[[0 1 2 1]]


In [63]:
print(x.shape, y.shape,'\n')
outer = x*y
print(outer,'\n')
print(outer.shape,'\n')

(4, 1) (1, 4) 

[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]] 

(4, 4) 



### https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html#table0101

### https://yeko90.tistory.com/46

https://donut-ts.tistory.com/18

### 메모리 카피 .copy() vs .view

In [68]:
a = np.arange(5)
b = a.copy() #카피를 하면 메모리를 공유하지 않고 새롭게 할당함.

b[0] = 100 #새 메모리의 변수의 값을 바꾼다고 원본도 바뀌지는 않음 
print(a) 
print(b)

[0 1 2 3 4]
[100   1   2   3   4]


In [70]:
a = np.arange(5)
b = a.view()

b[0] = 100

print(a)
print(b)

[100   1   2   3   4]
[100   1   2   3   4]


# flatten vs reval

In [80]:
a = np.random.randint(0, 10, (2,3)) 

print('변경 전 a : ', a)
b = a.flatten() #.copy를 자동으로 함. 메모리 공유 x
print('번경 전 b : ', b)
b[0]= 10
print('변경 후 a : ', a)
print('변경 후 b : ', b)

변경 전 a :  [[1 2 7]
 [5 6 8]]
번경 전 b :  [1 2 7 5 6 8]
변경 후 a :  [[1 2 7]
 [5 6 8]]
변경 후 b :  [10  2  7  5  6  8]


In [79]:
a = np.random.randint(0, 10, (2,3)) 

print('변경 전 a : ', a)
b = a.ravel() # 메모리 공유 함
print('번경 전 b : ', b)
b[0]= -10
print('변경 후 a : ', a)
print('변경 후 b : ', b)

변경 전 a :  [[2 2 7]
 [4 0 7]]
번경 전 b :  [2 2 7 4 0 7]
변경 후 a :  [[-10   2   7]
 [  4   0   7]]
변경 후 b :  [-10   2   7   4   0   7]


### 메모리 공유 확인 방법(.base)

In [85]:
a = np.arange(4)
b = a.flatten() # 메모리를 공유하지 않으므로 
print('변경 전',b)

b[0] = 0

print('b base  :', b.base is a, '\n')
print('a : ', a)
print('변경 후', b)

변경 전 [0 1 2 3]
b base  : False 

a :  [0 1 2 3]
변경 후 [0 1 2 3]


# torch tensor vs numpy

###2 dim

In [97]:
x = np.array([[2,3],[1,4]])
x

y = torch.from_numpy(x)
y
# x.shape

tensor([[2, 3],
        [1, 4]])

In [98]:
x.shape

(2, 2)

In [102]:
y.shape

torch.Size([2, 2])

### 1 dim

In [125]:
z = np.array( [[[2,3], [1,4]]
             ,[[2,4], [5,6]]
             ,[[1,8], [9,1]]])

z.shape

(3, 2, 2)

In [131]:
y = torch.from_numpy(z)
y.shape

torch.Size([3, 2, 2])

In [130]:
x = torch.tensor(y)
x.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


torch.Size([3, 2, 2])